export const styles = {
  tableContainerStyles: {
    minWidth: '964px',
    // height: '1341px',
    borderRadius: '16px',
    overflow: 'hidden',
    position: 'relative',
  },
  tableStyles: {
    borderCollapse: 'collapse',
    borderStyle: 'hidden',
    borderSpacing: 0,
    height: '100%',
  },
  tableCellStyles: {
    height: '48px',
    borderBottom: 'none',
    fontSize: '16px',
    // fontWeight: 700,
    padding: '0px',
    color: '#0D323F',
  },
  // timeTableCellStyles: {
  //   height: '48px',
  //   width: '80px',
  //   borderBottom: 'none',
  //   textAlign: 'center',
  //   verticalAlign: 'middle',
  //   fontWeight: 'bold',
  // },
  // appointmentTableCellStyles: {
  //   height: '48px',
  //   borderBottom: 'none',
  //   padding: 0,
  // },
  // redLineStyles: {
  //   position: 'absolute',
  //   width: '100%',
  //   height: '2px',
  //   backgroundColor: 'red',
  //   top: 0,
  //   '&::before': {
  //     content: '""',
  //     position: 'absolute',
  //     left: '0px',
  //     top: '-4px',
  //     width: '10px',
  //     height: '10px',
  //     backgroundColor: 'red',
  //     borderRadius: '50%',
  //   },
  // },
  // appointmentBoxStyles: {
  //   backgroundColor: true ? '#d3d3d3' : '#1BBDD4',
  //   borderRadius: '8px',
  //   color: 'white',
  //   padding: '8px',
  //   display: 'flex',
  //   flexDirection: 'column',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   height: '100%',
  //   width: '100%',
  //   boxSizing: 'border-box',
  // },
  // nonWorkingBoxStyles: {
  //   backgroundColor: '#d3d3d3',
  //   borderRadius: '8px',
  //   height: '100%',
  //   width: '100%',
  //   display: 'flex',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  // },
};
