export const styles = {
  container: { minWidth: '964px', borderRadius: '16px', overflow: 'hidden' },
  tableCell: { height: '48px', borderBottom: 'none' },
  timeSlotCell: {
    height: '48px',
    width: '80px',
    textAlign: 'center',
    verticalAlign: 'middle',
    fontWeight: 'bold',
  },
  appointmentBox: {
    borderRadius: '8px',
    color: 'white',
    padding: '8px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
    boxSizing: 'border-box',
  },
  nonWorkingBox: {
    backgroundColor: '#d3d3d3',
    borderRadius: '8px',
    height: '100%',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  redLine: {
    position: 'absolute',
    width: '100%',
    height: '2px',
    backgroundColor: 'red',
    top: 0,
    '&::before': {
      content: '""',
      position: 'absolute',
      left: '0px',
      top: '-4px',
      width: '10px',
      height: '10px',
      backgroundColor: 'red',
      borderRadius: '50%',
    },
  },
};
