export const styles = {
  tableContainerStyles: {
    minWidth: '964px',
    // height: '1341px',
    borderRadius: '16px',
    overflow: 'hidden',
    position: 'relative',
  },
  tableStyles: {
    borderCollapse: 'separate',
    borderSpacing: 0,
    height: '100%',
  },
  tableCellStyles: {
    height: '48px',
    borderBottom: 'none',
    fontWeight: 700,
  },
  timeTableCellStyles: {
    height: '48px',
    width: '80px',
    borderBottom: 'none',
    textAlign: 'center',
    verticalAlign: 'middle',
    fontWeight: 'bold',
  },
  appointmentTableCellStyles: {
    height: '48px',
    border: '1px solid #F2F4F7',
    // borderBottom: 'none',
    padding: 0,
  },
  redLineStyles: {
    position: 'absolute',
    width: '100%',
    height: '2px',
    backgroundColor: 'red',
    top: 0,
    '&::before': {
      content: '""',
      position: 'absolute',
      left: '0px',
      top: '-4px',
      width: '10px',
      height: '10px',
      backgroundColor: 'red',
      borderRadius: '50%',
    },
  },
  appointmentBoxStyles: {
    backgroundColor: '#1BBDD4',
    borderRadius: '4px',
    color: '#EEFCFD',
    padding: '0 2px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    height: '100%',
    width: '100%',
    boxSizing: 'border-box',
  },
  passedBoxStyles: {
    backgroundColor: '#d3d3d3',
  },
  nonWorkingBoxStyles: {
    backgroundColor: '#d3d3d3',
    borderRadius: '4px',
    color: '#576072',
    height: '100%',
    width: '100%',
    display: 'flex',
    // alignItems: 'flex-start',
    justifyContent: 'center',
  },
  appointmentTitleStyles: {
    fontWeight: 700,
  },
  patientVerticalBar: {
    backgroundColor: '#EEFCFD',
    borderRadius: '2px',
    width: '4px',
    height: '43px',
    marginRight: '8px',
  },
  patientContainer: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: '2px',
  },
  nonWorkingVerticalBar: {
    backgroundColor: '#576072',
  },
};
